aws:
  accessKeyID: accesskey
  secretAccessKey: secretkey
  region: region

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/dns-operator-aws"
  tag: "[[ .Version ]]"
registry:
  domain: docker.io

managementClusterName: ""
managementClusterNamespace: ""

pod:
  user:
    id: 1000
  group:
    id: 1000

verticalPodAutoscaler:
  enabled: true
