project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/dns-operator-aws"
  tag: "[[ .Version ]]"
Installation:
  V1:
    Registry:
      Domain: quay.io
pod:
  user:
    id: 1000
  group:
    id: 1000
