aws:
  accessKeyID: accesskey
  secretAccessKey: secretkey
  region: region

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/dns-operator-aws"
  tag: "[[ .Version ]]"
registry:
  domain: docker.io

managementClusterName: ""
managementClusterNamespace: ""


associateResolverRules: false

# Associate only resolver rules owned by this AWS Account
resolverRulesOwnerAccount: ""

pod:
  user:
    id: 1000
  group:
    id: 1000

verticalPodAutoscaler:
  enabled: true

# Add seccomp to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  seccompProfile:
    type: RuntimeDefault
